#!/usr/bin/env bash
tmux kill-session -t "TDBot"
tmux kill-session -t "Helper"

echo "Start Launch ...."
echo "█▒▒▒▒▒▒▒▒▒ 10%"
sleep 0.5
echo ""
echo ""
echo "██▒▒▒▒▒▒▒▒ 20%"
sleep 0.5
echo ""
echo ""
echo "███▒▒▒▒▒▒▒ 30%"
sleep 0.5
echo ""
echo ""
echo "████▒▒▒▒▒▒ 40%"
sleep 0.5
echo ""
echo ""
echo "█████▒▒▒▒▒ 50%"
sleep 0.5
echo ""
echo ""
echo "██████▒▒▒▒ 60%"
sleep 0.5
echo ""
echo ""
echo "███████▒▒▒ 70%"
sleep 0.5
echo ""
echo ""
echo "████████▒▒ 80%"
sleep 0.5
echo ""
echo ""
echo "█████████▒ 90%"
sleep 0.5
echo ""
echo ""
echo "██████████ 100%"
sleep 1
echo "Base TDBot ( gladiator )"
sleep 0.7
echo ""
echo "Edit By @didi47"
sleep 0.7
echo ""
echo "Channel @ragnarbot2"
sleep 2
tmux new-session -d -s "TDBot" "./Data/TDBot"
tmux detach -s "TDBot"
echo "Cli and Api Now Running!"
echo "... The terminal is Closed ..."
sleep 5
tmux new-session -d -s "Helper" "./Data/Helper"
tmux detach -s "Api"
